#define R_COLOR_SCHEME_DEFAULT -1
#define R_COLOR_SCHEME_TEXT 0
#define R_COLOR_SCHEME_HOVERED 1
#define R_COLOR_SCHEME_SELECTED 2
#define R_COLOR_SCHEME_SELECTED_HOVERED 3
#define R_COLOR_SCHEME_SELECTED_BODY 4
#define R_COLOR_SCHEME_DELETE 5
#define R_COLOR_SCHEME_DELETE_HOVERED 6
#define R_COLOR_SCHEME_DELETE_BODY 7

#define R_TEXT_COLOR XT_CH_GREEN

#define R_HOVERED_BG_COLOR XT_BG_GREEN
#define R_HOVERED_TEXT_COLOR XT_CH_WHITE

#define R_SELECTED_BG_COLOR XT_BG_CYAN
#define R_SELECTED_TEXT_COLOR XT_CH_BLUE
#define R_SELECTED_BODY_COLOR XT_CH_BLUE
#define R_SELECTED_TEXT_STYLE XT_CH_BOLD
#define R_SELECTED_BODY_STYLE XT_CH_NORMAL
#define R_SELECTED_HOVERED_TEXT_COLOR XT_CH_RED

#define R_DELETE_TEXT_COLOR XT_CH_YELLOW
#define R_DELETE_BG_COLOR XT_BG_RED
#define R_DELETE_TEXT_STYLE XT_CH_BOLD
#define R_DELETE_BODY_STYLE XT_CH_NORMAL

void setColor(int colorScheme);